examples/plot_grad_search_cv.py
examples/plot_held_out_lasso.py
examples/plot_sparse_log_reg.py

I still get a print statements. Could we hide this using the verbose parameter?

nicer examples

---

examples/plot_held_out_lasso.py
sparse_ho/ho.py
sparse_ho/implicit_forward.py
sparse_ho/models.py
sparse_ho/tests/test_elastic.py
sparse_ho/utils.py

Elasticnet

---

sparse_ho/criterion.py

The goal of this PR is to pass a proper sklearn estimator to the model object, ie avoiding this:
https://github.com/QB3/sparse-ho/blob/20148e1508dbbe11e76919ee0b1ec3b24886791d/sparse_ho/models.py#L34

ENH pass proper sklearn estimator

---

examples/plot_held_out_enet.py
examples/plot_held_out_lasso.py
expes/expe_elastic/main_heatmap.py

The goal is to add an example with enet with 2 hyperparameters

Add enet example

---

doc/api.rst
examples/plot_wlasso.py
sparse_ho/models.py
sparse_ho/tests/test_lasso.py

This is an improved example of the wLasso example, wdyt @josephsalmon and @ksehic ?

Improved wLasso example

---

examples/plot_grad_search_cv.py
examples/plot_held_out_enet.py
examples/plot_held_out_lasso.py
examples/plot_sparse_log_reg.py
examples/plot_wlasso.py
sparse_ho/backward.py
sparse_ho/criterion.py
sparse_ho/forward.py
sparse_ho/grid_search.py
sparse_ho/ho.py
sparse_ho/hyperopt_wrapper.py
sparse_ho/implicit.py
sparse_ho/implicit_forward.py
sparse_ho/tests/test_elastic.py
sparse_ho/tests/test_grad_search.py
sparse_ho/tests/test_grad_search_CV.py
sparse_ho/tests/test_grid_search.py
sparse_ho/tests/test_lasso.py
sparse_ho/tests/test_logreg.py
sparse_ho/tests/test_svm.py

trying to breakdown API change in smaller pieces :)

WIP: Criterion not being an attribute of Algo

---

doc/api.rst
sparse_ho/criterion.py
sparse_ho/tests/test_grad_search.py
sparse_ho/tests/test_grid_search.py
sparse_ho/tests/test_lasso.py
sparse_ho/tests/test_svm.py

Fix (partly) issue #39.
Waiting for more input for renaming the class.

WIP: SURE class api

---

setup.cfg
sparse_ho/criterion.py
sparse_ho/forward.py
sparse_ho/grid_search.py
sparse_ho/implicit.py
sparse_ho/implicit_forward.py
sparse_ho/models.py
sparse_ho/tests/test_elastic.py
sparse_ho/tests/test_grad_search.py
sparse_ho/tests/test_grid_search.py
sparse_ho/tests/test_logreg.py
sparse_ho/tests/test_monitor.py
sparse_ho/tests/test_svm.py
sparse_ho/tests/test_svr.py

in particular lines longer than 80 characters

MRG ENH: stop ignoring flake8 errors

---

doc/api.rst
sparse_ho/criterion/__init__.py
sparse_ho/criterion/sure.py
sparse_ho/tests/test_grad_search.py
sparse_ho/tests/test_grid_search.py
sparse_ho/tests/test_lasso.py

PR to change the current name of the SURE criterion: SmoothedSure >> FiniteDiffMonteCarloSure.
closes #39

Change name sure

---

sparse_ho/optimizers/gradient_descent.py

Avoid 0 division in gradient descent, thx to the bug catch from @ksehic

ENH avoid 0division in gd

---

examples/plot_wlasso.py
sparse_ho/optimizers/gradient_descent.py
sparse_ho/optimizers/line_search.py

Display gradient norm for the outer optimization problem for the line search
closes #60

ENH display grad norm in line search + modified example wLasso

---

sparse_ho/algo/forward.py
sparse_ho/models/enet.py
sparse_ho/models/lasso.py
sparse_ho/models/logreg.py
sparse_ho/tests/test_models.py
sparse_ho/utils.py

The goal of this PR is to add more serious stopping criterion for our estimators, in order for the checkgrad tolerance in the test to be super low

ENH added dual gap stop crit

---

examples/plot_held_out_enet.py
sparse_ho/optimizers/gradient_descent.py

PR to remove the 3D plot for the enet

Improve enet example

---

examples/plot_compare_optimizers.py
examples/plot_held_out_enet.py
examples/plot_held_out_lasso.py
examples/plot_lassoCV.py
examples/plot_sparse_log_reg.py
examples/plot_wlasso.py
sparse_ho/grid_search.py
sparse_ho/optimizers/adam.py

A few tweaks to the enet example.
The gradients do not go to 0, is that normal ?
```
Iteration 23/25 ||Value outer criterion: 1.56e+04 ||norm grad 3.13e+02
Iteration 24/25 ||Value outer criterion: 1.56e+04 ||norm grad 1.03e+02
Iteration 25/25 ||Value outer criterion: 1.56e+04 ||norm grad 1.33e+02
```
a thought is that the crosses could be linked with small lines to show the optimization path, do you think it's too crowded @Klopfe @QB3 ?

[MRG] DOC: pass on examples

---

examples/plot_compare_optimizers.py
examples/plot_held_out_enet.py
examples/plot_held_out_lasso.py
examples/plot_sparse_log_reg.py
sparse_ho/grid_search.py
sparse_ho/tests/test_grid_search.py

ENH changed color map + rm algo param from grid search

---

.github/workflows/build.yml
README.rst

fix link in readme (does not fix image)

---

sparse_ho/models/svm.py
sparse_ho/models/svr.py
sparse_ho/tests/test_utils.py

@Klopfe see this as inspiration and have a look at my XXX comments.
please take over by pushing directly on this PR.

factorize some code to remove code dupe

---

sparse_ho/tests/common.py
sparse_ho/tests/test_models.py

A weird bug is happening with the CI when testing the SVR.
This does not happend in local.
I just commented the test of the SVR for this PR in order to make the CI green.
I propose to fix this pb in another PR.

removed svr testing

---

README.rst

MRG: rewrite readme: name of supported models, link to doc, update bib

---

doc/api.rst
sparse_ho/algo/backward.py
sparse_ho/algo/forward.py
sparse_ho/algo/implicit_forward.py
sparse_ho/ho.py
sparse_ho/tests/test_docstring_parameters.py

It's a pain to fix the first time but then it'll do you a tremendous favor @QB3 
you can ignore some functions in `docstring_ignores`, I've left a celer example on purpose

[MRG] DOC/TEST Add test_docstring_parameters

---

doc/api.rst
examples/plot_compare_optimizers.py
examples/plot_held_out_enet.py
examples/plot_sparse_log_reg.py
sparse_ho/algo/forward.py
sparse_ho/algo/implicit.py
sparse_ho/algo/implicit_forward.py
sparse_ho/criterion/held_out.py
sparse_ho/models/enet.py
sparse_ho/models/lasso.py
sparse_ho/models/logreg.py
sparse_ho/models/svm.py
sparse_ho/models/svr.py
sparse_ho/models/wlasso.py
sparse_ho/tests/test_docstring_parameters.py
sparse_ho/tests/test_optimizers.py

After writing this I think Lasso, ElasticNet, WeightedLasso and Logistic regression could inherit from a common class. This would make a lot of code less duplicated.
I think it allowed me to catch a few bugs. I have written lots of TODO.
closes #110

Write and test docstrings for models

---

doc/api.rst
examples/plot_held_out_enet.py
examples/plot_wlasso.py
expes/expe_enet/main_enet_pred.py
expes/expe_enet/plot_enet_pred.py
expes/expe_fig_cross_val/main_crossval.py
expes/expe_fig_cross_val/main_crossval_elastic.py
expes/expe_lasso/main_lasso_pred.py
expes/expe_lasso/plot_lasso_pred.py
expes/multiclass/plot_multiclass.py
sparse_ho/algo/forward.py
sparse_ho/criterion/cross_val.py
sparse_ho/criterion/held_out.py
sparse_ho/criterion/multiclass_logreg.py
sparse_ho/criterion/sure.py
sparse_ho/models/enet.py
sparse_ho/models/lasso.py
sparse_ho/models/logreg.py
sparse_ho/models/svm.py
sparse_ho/models/svr.py
sparse_ho/models/wlasso.py
sparse_ho/optimizers/adam.py
sparse_ho/optimizers/gradient_descent.py
sparse_ho/optimizers/line_search.py
sparse_ho/tests/test_docstring_parameters.py

Still somes fixes to do, feel free to push to the branch @QB3

[MRG] ENH: Start testing criterion, datasets, optimizer

---

doc/api.rst
sparse_ho/models/enet.py
sparse_ho/models/lasso.py
sparse_ho/models/logreg.py
sparse_ho/models/svm.py
sparse_ho/models/svr.py
sparse_ho/models/wlasso.py
sparse_ho/optimizers/adam.py
sparse_ho/optimizers/line_search.py

Harmonize what appears on the API doc webpage

DOC: First line of docstrings for models and optimizers

---

examples/plot_compare_optimizers.py
examples/plot_held_out_enet.py
examples/plot_held_out_lasso.py
examples/plot_lassoCV.py
examples/plot_sparse_log_reg.py
examples/plot_use_callback.py
expes/multiclass/main_multiclass.py
expes/multiclass/plot_multiclass.py
sparse_ho/datasets/utils_datasets.py
sparse_ho/tests/test_multiclass.py

closes #112 
It remains to add docstrings 
@QB3 can you check that the new way to do the stratified split behaves the same? Btw having mutable arguments as default (here, stratified shuffle split) is a bad design, as they are instanciated only once (stored in `my_function.__defaults__`) and then modifying them inside the functions modifies the default value)

Cleanup utils_datasets

---

sparse_ho/algo/implicit_forward.py
sparse_ho/models/enet.py
sparse_ho/models/lasso.py
sparse_ho/models/logreg.py
sparse_ho/models/svm.py
sparse_ho/models/svr.py
sparse_ho/models/wlasso.py
sparse_ho/tests/test_docstring_parameters.py
sparse_ho/tests/test_models.py

This is the reason why tests are slow.

[FIX] Fix warm start and stopping criterion for Jacobian computation
